version: '3.9'

services:
  apache:
    image: httpd:latest
    restart: always
    container_name: http-container
    ports:
      - '80:80'
    volumes:
      - /home/gustavo/Documents/Programação/Docker/Desafio-DIO/Web:/usr/local/apache2/htdocs
    networks:
      - my-net

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "MyPassword"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /home/gustavo/Documents/Programação/Docker/Desafio-DIO/SQL:/var/lib/mysql
    networks:
      - my-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "MyPassword"
    ports:
      - "8080:80"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge

